import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar'





export default function Home() {

  return (
    <div className={styles.container}>
      <NavBar></NavBar>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="btn btn-primary">Button</button>

    </div>
  )
}
